### ISSUE TITLE
Bug Report | course time, create date and other text inside app not showing but outline shows

### ISSUE THREAD

**Issue by lundeen-bryan** [tadwohlrapp/udemy-improved-course-library#8]
Great extension, i wish they hired you to do the UX/UI for the Udemy site! I noticed the extension is not showing the text links inside the area where the course shows in the library. I tried clearing cookies and logging back in, but still saw the problem. 
See screenshot: https://imagizer.imageshack.com/a/img924/8720/CcU0cD.jpg

browser: Microsoft Edge Version 114.0.1823.24 (Official build) beta (64-bit)

**Comment by lundeen-bryan** [comment]
Tried it in private mode and it's still not working. 
I'm surprised nobody else is reporting an issue.

**Comment by tadwohlrapp** [comment]
Hey @lundeen-bryan, apologies for taking so long to respond! 

You're absolutely right, the extension is broken due to a recent markup change introduced on Udemy's site.
Thank you for bringing it to my attention!

I will publish a fixed version as soon as possible. Thank you for your patience!

**Comment by tadwohlrapp** [comment]
Keeping the issue open until the fixed version v1.1.1 is live on all stores.

Current status:

|                  | Submitted | Published |
|------------------|-----------|-----------|
| Chrome Web Store | ✅         | ✅         |
| Mozilla Add-ons  | ✅         | ✅         |
| Edge Add-ons     | ✅         | ✅         |
| Greasy Fork      | ✅         | ✅         |

**Comment by lundeen-bryan** [comment]
Thank you SO much Tad! Fixed and working like a charm again! Tested in Microsoft Edge Version 114.0.1823.37 (Official build) beta (64-bit). Ext was installed via Chrome web store.

**Comment by Jalil02** [comment]
I still have same problem on Chrome and Edge. I was using Chrome Web Store version on both. Tried to use with userscript but nothing changed.

Google Chrome 114.0.5735.199 (Official build) (64-bit)
Microsoft Edge 115.0.1901.203 (Official build) (64-bit)

![udemy_issue](https://github.com/tadwohlrapp/udemy-improved-course-library/assets/55533255/2708726a-1267-4cd7-af0b-3dc39e5c5b1d)
